version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
            - "3000:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/web"
        depends_on:
            - "php"
            - "mysqldb"
    php:
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ./web:/web
    composer:
        image: composer/composer
        volumes:
            - ./web/app:/app
        command: install
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - "mysqldb"
    mysqldb:
        image: mysql
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=1234
        ports:
            - 3306:3306
        volumes:
            - ./data/db/mysql:/var/lib/mysql
